import config from './config.json'

let RECAPTCHA_SITEKEY = config.RECAPTCHA_SITEKEY
let API_URL = config.API_URL
let MESSAGEDATA = {}
MESSAGEDATA.RESET_PASSWORD_TITLE = config.RESET_PASSWORD_TITLE
MESSAGEDATA.COMMON_TITLE = config.COMMON_TITLE
MESSAGEDATA.ORDER_SUCCESS_TITLE = config.ORDER_SUCCESS_TITLE
MESSAGEDATA.TERMS_AND_CONDITIONS_TITLE = config.TERMS_AND_CONDITIONS_TITLE
MESSAGEDATA.EMAIL_VERIFIED_TITLE = config.EMAIL_VERIFIED_TITLE

MESSAGEDATA.RESET_PASSWORD_INFO = config.RESET_PASSWORD_INFO
MESSAGEDATA.RESET_PASSWORD_SUCCESS = config.RESET_PASSWORD_SUCCESS
MESSAGEDATA.RESET_PASSWORD_ERROR = config.RESET_PASSWORD_ERROR
MESSAGEDATA.COMMON_ERROR = config.COMMON_ERROR
MESSAGEDATA.ORDER_SUCCESS = config.ORDER_SUCCESS
MESSAGEDATA.TERMS_AND_CONDITIONS = config.TERMS_AND_CONDITIONS
MESSAGEDATA.SERVER_ERROR = config.SERVER_ERROR
MESSAGEDATA.CHECKOUT_INFO = config.CHECKOUT_INFO
MESSAGEDATA.PAYPAL_RESPONSE_ERROR = config.PAYPAL_RESPONSE_ERROR
MESSAGEDATA.EXPIRED_ORDER_ERROR = config.EXPIRED_ORDER_ERROR
MESSAGEDATA.DEFAULT_ORDER_ERROR = config.DEFAULT_ORDER_ERROR
MESSAGEDATA.ORDER_CANCEL_INFO = config.ORDER_CANCEL_INFO
MESSAGEDATA.PAYMENT_CANCEL_INFO = config.PAYMENT_CANCEL_INFO
MESSAGEDATA.EXPORTED_DOMAINS_SUCCESS = config.EXPORTED_DOMAINS_SUCCESS
MESSAGEDATA.AGREE_INFO = config.AGREE_INFO
MESSAGEDATA.PAYPAL_REDIRECT_INFO = config.PAYPAL_REDIRECT_INFO
MESSAGEDATA.ORDER_FAILED_TITLE = config.ORDER_FAILED_TITLE
MESSAGEDATA.ADD_CREDIT_INFO = config.ADD_CREDIT_INFO

if (process.env.NODE_ENV == 'production') {
  API_URL = 'https://www.sesprout.com/api'
}
if (process.env.NODE_ENV == 'staging') {
	API_URL = config.TEST_SERVER
}

export default { API_URL, RECAPTCHA_SITEKEY,MESSAGEDATA }
